const $=(s,e=document)=>e.querySelector(s), $$=(s,e=document)=>[...e.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const INR_USD=85;
const state={products:[],cart:JSON.parse(localStorage.getItem('bg_cart')||'[]'),token:localStorage.getItem('bg_token')||'',user:null,adminToken:localStorage.getItem('bg_admin')||'',currency:localStorage.getItem('bg_cur')||'INR'};
const shop={q:'',cat:'All',sort:'featured'};
const money=n=>state.currency==='USD'?'$'+Math.round(n/INR_USD):'₹'+Number(n).toLocaleString('en-IN');
async function api(path,opt={}){const h={};if(opt.body)h['Content-Type']='application/json';if(opt.auth==='user'&&state.token)h.Authorization='Bearer '+state.token;if(opt.auth==='admin'&&state.adminToken)h.Authorization='Bearer '+state.adminToken;const r=await fetch(path,{method:opt.method||'GET',headers:h,body:opt.body?JSON.stringify(opt.body):undefined});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||'HTTP '+r.status);return d}
function saveCart(){localStorage.setItem('bg_cart',JSON.stringify(state.cart));badge()}
function badge(){const b=$('#cartBadge');if(b)b.textContent=state.cart.reduce((n,x)=>n+x.qty,0)}
function add(id,qty=1){let x=state.cart.find(i=>i.id===id);x?x.qty=Math.min(10,x.qty+qty):state.cart.push({id,qty:Math.min(10,qty)});saveCart();toast('Added to cart')}
function remove(id){state.cart=state.cart.filter(i=>i.id!==id);saveCart();render()}
function setQty(id,qty){const x=state.cart.find(i=>i.id===id);if(x)x.qty=Math.max(1,Math.min(10,qty));saveCart();render()}
function lines(){return state.cart.map(i=>({i,p:state.products.find(p=>p.id===i.id)})).filter(x=>x.p)}
function subtotal(){return lines().reduce((s,x)=>s+x.p.price_inr*x.i.qty,0)}
function nav(u){history.pushState({},'',u);render()}
function meta(t,d){document.title=t;const m=$('meta[name="description"]');if(m)m.content=d||''}
function card(p){return '<article class="card"><a class="card-media" href="/product/'+p.id+'"><img src="'+p.img+'" alt="'+esc(p.name)+'" loading="lazy" onerror="this.style.display=\'none\'"><span class="badge">'+esc((p.badges||[])[0]||'Pick')+'</span></a><div class="card-body"><span class="card-cat">'+esc(p.category)+'</span><a class="card-name" href="/product/'+p.id+'">'+esc(p.name)+'</a><div class="card-price"><strong>'+money(p.price_inr)+'</strong>'+(p.compare_at_inr?'<s>'+money(p.compare_at_inr)+'</s>':'')+'</div><button class="btn btn-primary btn-block" onclick="event.preventDefault();add(\''+p.id+'\')">Add to Cart</button></div></article>'}
function renderAuth(){const a=$('#authArea');if(!a)return;a.innerHTML=state.user?'<a href="/account" class="nav-auth">👤 '+esc(state.user.name.split(' ')[0])+'</a>':'<a href="/login" class="nav-auth">Login</a>'}
function home(){meta('BBest Globly — Everyday Upgrades | India & Worldwide','Trending tech, wellness, home and pet products — curated for India and worldwide.');const cats=[...new Set(state.products.map(p=>p.category))];$('#app').innerHTML='<section class="hero"><div class="hero-bg" style="background-image:url(\'img/hero.jpg\')"></div><div class="hero-in wrap"><span class="hero-kicker">✦ New arrivals · 2026 collection</span><h1>Everyday upgrades,<br>curated for India &amp; the world.</h1><p>Trending tech, wellness and home picks — hand-picked, honestly priced, delivered to your door.</p><div class="hero-cta"><a class="btn btn-primary" href="/shop">Shop Now</a><a class="btn btn-hero-ghost" href="/track">Track Order</a></div></div></section><section class="wrap"><div class="value-row"><div class="value"><span class="v-ico">🎯</span><div><strong>Curated catalogue</strong><span>Trending, problem-solving picks</span></div></div><div class="value"><span class="v-ico">💵</span><div><strong>Cash on Delivery</strong><span>Pay when your order arrives</span></div></div><div class="value"><span class="v-ico">📦</span><div><strong>Order tracking</strong><span>Every order gets a tracking ID</span></div></div></div><h2 class="section-title">Shop by category</h2><div class="chips">'+cats.map(c=>'<button class="chip" onclick="goShop(\''+esc(c)+'\')">'+esc(c)+'</button>').join('')+'</div><h2 class="section-title">Trending now</h2><div class="grid">'+state.products.map(card).join('')+'</div></section>'}
function shopPage(){meta('Shop — BBest Globly','Browse trending products from BBest Globly.');const cats=['All',...new Set(state.products.map(p=>p.category))];$('#app').innerHTML='<section class="page"><h1>Shop</h1><p class="muted">'+state.products.length+' curated products · India &amp; worldwide</p><div class="toolbar"><input id="q" type="search" placeholder="Search products…" value="'+esc(shop.q)+'"><select id="sort"><option value="featured">Featured</option><option value="price-asc">Price: Low → High</option><option value="price-desc">Price: High → Low</option></select></div><div class="chips" id="cats">'+cats.map(c=>'<button class="chip '+(c===shop.cat?'on':'')+'" data-cat="'+esc(c)+'">'+esc(c)+'</button>').join('')+'</div><div class="grid" id="grid"></div></section>';$('#q').oninput=e=>{shop.q=e.target.value;drawShop()};$('#sort').value=shop.sort;$('#sort').onchange=e=>{shop.sort=e.target.value;drawShop()};$$('#cats .chip').forEach(b=>b.onclick=()=>{shop.cat=b.dataset.cat;$$('#cats .chip').forEach(x=>x.classList.toggle('on',x===b));drawShop()});drawShop()}
function drawShop(){let a=state.products.filter(p=>(shop.cat==='All'||p.category===shop.cat)&&(p.name+' '+p.category+' '+p.tagline).toLowerCase().includes(shop.q.toLowerCase()));if(shop.sort==='price-asc')a=a.slice().sort((x,y)=>x.price_inr-y.price_inr);if(shop.sort==='price-desc')a=a.slice().sort((x,y)=>y.price_inr-x.price_inr);$('#grid').innerHTML=a.length?a.map(card).join(''):'<p class="empty">No products match your search.</p>'}
function product(id){const p=state.products.find(x=>x.id===id);if(!p)return notFound();meta(p.name+' — BBest Globly',p.tagline);$('#app').innerHTML='<section class="page"><p class="breadcrumb"><a href="/">Home</a> / <a href="/shop">Shop</a> / '+esc(p.category)+'</p><div class="pd"><div class="pd-media"><img src="'+p.img+'" alt="'+esc(p.name)+'" onerror="this.style.display=\'none\'"></div><div class="pd-info"><span class="card-cat">'+esc(p.category)+'</span><h1>'+esc(p.name)+'</h1><p class="tagline">'+esc(p.tagline)+'</p><div class="pd-price">'+money(p.price_inr)+(p.compare_at_inr?'<s>'+money(p.compare_at_inr)+'</s>':'')+'</div><p class="desc">'+esc(p.description)+'</p><ul class="features">'+(p.features||[]).map(f=>'<li>'+esc(f)+'</li>').join('')+'</ul><div class="pd-actions"><button class="btn btn-primary" onclick="add(\''+p.id+'\')">Add to Cart</button><a class="btn btn-outline" href="/cart">Go to Cart</a></div></div></div></section>'}
function cart(){meta('Cart — BBest Globly');const ls=lines();$('#app').innerHTML='<section class="page"><h1>Your Cart</h1>'+(!ls.length?'<p class="empty">Your cart is empty. <a href="/shop" style="color:var(--accent);font-weight:700">Shop now →</a></p>':'<div class="co"><div>'+ls.map(x=>'<div class="cart-line"><img src="'+x.p.img+'" alt=""><div><a class="card-name" href="/product/'+x.p.id+'">'+esc(x.p.name)+'</a><div class="muted">'+money(x.p.price_inr)+' × '+x.i.qty+'</div><div class="qty"><button onclick="setQty(\''+x.p.id+'\','+(x.i.qty-1)+')">−</button><span>'+x.i.qty+'</span><button onclick="setQty(\''+x.p.id+'\','+(x.i.qty+1)+')">+</button></div></div><button class="link-danger" onclick="remove(\''+x.p.id+'\')">Remove</button></div>').join('')+'</div><aside class="summary"><h3>Order summary</h3><div class="sum-row"><span>Subtotal</span><strong>'+money(subtotal())+'</strong></div><div class="sum-row"><span>Shipping</span><span>Calculated at checkout</span></div><div class="sum-row total"><span>Total</span><strong>'+money(subtotal())+'</strong></div><a class="btn btn-primary btn-block" href="/checkout">Checkout</a></aside></div>')}
function checkout(){meta('Checkout — BBest Globly');if(!lines().length)return nav('/cart');$('#app').innerHTML='<section class="page"><h1>Checkout</h1><div class="co"><div class="summary"><h3>Customer details</h3><div class="form-grid"><div><label>Name</label><input id="name"></div><div><label>Phone</label><input id="phone"></div><div class="full"><label>Email</label><input id="email" type="email"></div><div class="full"><label>Address</label><textarea id="address" rows="3"></textarea></div><div><label>City</label><input id="city"></div><div><label>State</label><input id="state"></div><div><label>Pincode</label><input id="pincode"></div><div><label>Country</label><input id="country" value="India"></div></div><h3 class="form-title">Payment</h3><div class="radio-card on"><strong>Cash on Delivery</strong><span>Pay when your order arrives</span></div><p id="coErr" class="form-err"></p><button id="place" class="btn btn-primary btn-block">Place COD Order · '+money(subtotal())+'</button></div><aside class="summary"><h3>Items</h3>'+lines().map(x=>'<div class="sum-row"><span>'+esc(x.p.name)+' ×'+x.i.qty+'</span><strong>'+money(x.p.price_inr*x.i.qty)+'</strong></div>').join('')+'<div class="sum-row total"><span>Total</span><strong>'+money(subtotal())+'</strong></div></aside></div></section>';$('#place').onclick=async()=>{const b={name:$('#name').value,phone:$('#phone').value,email:$('#email').value,address:$('#address').value,city:$('#city').value,state:$('#state').value,pincode:$('#pincode').value,country:$('#country').value,payment_method:'cod',items:lines().map(x=>({id:x.p.id,qty:x.i.qty}))};try{const d=await api('/api/orders',{method:'POST',body:b});state.cart=[];saveCart();nav('/order/'+d.orderId)}catch(e){$('#coErr').textContent=e.message}}}
async function order(id){meta('Order '+id+' — BBest Globly');$('#app').innerHTML='<section class="page"><p class="empty">Loading order…</p></section>';try{const o=await api('/api/order/'+id);$('#app').innerHTML='<section class="page"><div class="success-box"><h1>Order placed 🎉</h1><p>Your order ID</p><div class="order-id">'+esc(o.id)+'</div><p><span class="status-pill">'+esc(o.status)+'</span></p><p>Total: <strong>₹'+Number(o.totals.total_inr).toLocaleString('en-IN')+'</strong></p><a class="btn btn-primary" href="/track">Track order</a></div></section>'}catch(e){notFound()}}
async function track(){meta('Track Order — BBest Globly');$('#app').innerHTML='<section class="page"><div class="auth-card"><h1>Track your order</h1><p class="sub">Enter your BBest Globly order ID.</p><div class="field"><label>Order ID</label><input id="oid" placeholder="BG-..."></div><p id="terr" class="form-err"></p><button id="tb" class="btn btn-primary btn-block">Track</button></div></section>';$('#tb').onclick=async()=>{try{const o=await api('/api/order/'+encodeURIComponent($('#oid').value.trim()));$('#terr').textContent='';$('#app').innerHTML='<section class="page"><div class="success-box"><h1>Order '+esc(o.id)+'</h1><p><span class="status-pill">'+esc(o.status)+'</span></p><p>Total ₹'+Number(o.totals.total_inr).toLocaleString('en-IN')+'</p></div></section>'}catch(e){$('#terr').textContent=e.message}}}
function login(){authForm(false)}
function register(){authForm(true)}
function authForm(reg){meta(reg?'Create Account — BBest Globly':'Login — BBest Globly');$('#app').innerHTML='<section class="page"><div class="auth-card"><h1>'+(reg?'Create your account':'Welcome back')+'</h1><p class="sub">'+(reg?'Track orders and checkout faster.':'Log in to your BBest Globly account.')+'</p>'+(reg?'<div class="field"><label>Name</label><input id="nm"></div>':'')+(reg?'<div class="field"><label>Phone</label><input id="ph"></div>':'')+'<div class="field"><label>Email</label><input id="em" type="email"></div><div class="field"><label>Password</label><input id="pw" type="password"></div><p id="aerr" class="form-err"></p><button id="ab" class="btn btn-primary btn-block">'+(reg?'Create account':'Login')+'</button><p class="auth-link">'+(reg?'Already have an account? <a href="/login">Login</a>':'New here? <a href="/register">Create an account</a>')+'</p></div></section>';$('#ab').onclick=async()=>{try{const body=reg?{name:$('#nm').value,phone:$('#ph').value,email:$('#em').value,password:$('#pw').value}:{email:$('#em').value,password:$('#pw').value};const d=await api(reg?'/api/auth/register':'/api/auth/login',{method:'POST',body});state.token=d.token;state.user=d.customer;localStorage.setItem('bg_token',state.token);nav('/account')}catch(e){$('#aerr').textContent=e.message}}}
async function account(){if(!state.token)return nav('/login');try{const me=await api('/api/auth/me',{auth:'user'}),os=await api('/api/my/orders',{auth:'user'});state.user=me;meta('My Account — BBest Globly');$('#app').innerHTML='<section class="page" style="max-width:900px"><h1>My Account</h1><div class="co"><div class="summary"><h3>Profile</h3><div class="profile-row"><span>Name</span><strong>'+esc(me.name)+'</strong></div><div class="profile-row"><span>Email</span><strong>'+esc(me.email)+'</strong></div><div class="profile-row"><span>Phone</span><strong>'+esc(me.phone||'—')+'</strong></div><button id="logout" class="btn btn-outline btn-block" style="margin-top:16px">Logout</button></div><div><h3 style="margin-top:0">Order history ('+os.length+')</h3>'+(os.length?os.map(o=>'<div class="cart-line" style="grid-template-columns:1fr auto"><div><a class="card-name" href="/order/'+o.id+'">'+esc(o.id)+'</a><div class="muted">'+new Date(o.created).toLocaleString('en-IN')+'</div></div><div><strong>₹'+Number(o.totals.total_inr).toLocaleString('en-IN')+'</strong><br><span class="st">'+esc(o.status)+'</span></div></div>').join(''):'<p class="muted">No orders yet.</p>')+'</div></div></section>';$('#logout').onclick=async()=>{try{await api('/api/auth/logout',{method:'POST',auth:'user'})}catch{}state.token='';state.user=null;localStorage.removeItem('bg_token');nav('/')}}catch(e){state.token='';localStorage.removeItem('bg_token');nav('/login')}}
async function admin(){if(!state.adminToken)return adminLogin();try{const [s,os]=await Promise.all([api('/api/admin/stats',{auth:'admin'}),api('/api/admin/orders',{auth:'admin'})]);meta('Admin — BBest Globly');$('#app').innerHTML='<section class="page"><h1>Admin Dashboard</h1><div class="stat-grid"><div class="stat"><div class="n">'+s.orders+'</div><div class="l">Orders</div></div><div class="stat"><div class="n">'+s.pending+'</div><div class="l">Pending</div></div><div class="stat"><div class="n">₹'+Number(s.revenue_inr).toLocaleString('en-IN')+'</div><div class="l">Revenue</div></div><div class="stat"><div class="n">'+s.customers+'</div><div class="l">Customers</div></div></div><div class="table-wrap"><table class="tbl"><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Status</th></tr></thead><tbody>'+(os.length?os.map(o=>'<tr><td>'+esc(o.id)+'</td><td>'+esc(o.customer.name)+'</td><td>₹'+Number(o.totals.total_inr).toLocaleString('en-IN')+'</td><td><select class="mini" data-id="'+o.id+'">'+['PENDING','CONFIRMED','SHIPPED','DELIVERED','CANCELLED'].map(x=>'<option '+(x===o.status?'selected':'')+'>'+x+'</option>').join('')+'</select></td></tr>').join(''):'<tr><td colspan="4">No orders yet.</td></tr>')+'</tbody></table></div></section>';$$('.mini').forEach(s=>s.onchange=async()=>{try{await api('/api/admin/order-status',{method:'POST',auth:'admin',body:{id:s.dataset.id,status:s.value}});toast('Status updated')}catch(e){toast(e.message);admin()}})}catch(e){state.adminToken='';localStorage.removeItem('bg_admin');adminLogin()}}
function adminLogin(){meta('Admin Login — BBest Globly');$('#app').innerHTML='<section class="page"><div class="auth-card"><h1>Admin Login</h1><div class="field"><label>Username</label><input id="au" value="admin"></div><div class="field"><label>Password</label><input id="ap" type="password"></div><p id="aerr" class="form-err"></p><button id="alb" class="btn btn-primary btn-block">Login</button></div></section>';$('#alb').onclick=async()=>{try{const d=await api('/api/admin/login',{method:'POST',body:{username:$('#au').value,password:$('#ap').value}});state.adminToken=d.token;localStorage.setItem('bg_admin',d.token);admin()}catch(e){$('#aerr').textContent=e.message}}}
function goShop(cat){shop.cat=cat;nav('/shop')}
function notFound(){meta('Page Not Found — BBest Globly');$('#app').innerHTML='<section class="page" style="text-align:center"><h1>Page not found</h1><a class="btn btn-primary" href="/">Back Home</a></section>'}
function toast(msg){let t=$('#toast');if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>t.classList.remove('show'),2200)}
function render(){renderAuth();badge();const p=location.pathname.replace(/\/+$/,'')||'/';if(p==='/')home();else if(p==='/shop')shopPage();else if(p==='/cart')cart();else if(p==='/checkout')checkout();else if(p==='/track')track();else if(p==='/login')login();else if(p==='/register')register();else if(p==='/account')account();else if(p==='/admin')admin();else if(p.startsWith('/product/'))product(p.split('/')[2]);else if(p.startsWith('/order/'))order(p.split('/')[2]);else notFound()}
document.addEventListener('click',e=>{const a=e.target.closest('a');if(!a)return;const h=a.getAttribute('href')||'';if(h.startsWith('/')&&!h.startsWith('//')){e.preventDefault();nav(h)}});window.addEventListener('popstate',render);
(async()=>{try{state.products=await api('/api/products');if(state.token){try{state.user=await api('/api/auth/me',{auth:'user'})}catch{state.token='';localStorage.removeItem('bg_token')}}}catch{state.products=[]}const inr=$('#curINR'),usd=$('#curUSD');if(inr)inr.onclick=()=>{state.currency='INR';localStorage.setItem('bg_cur','INR');render()};if(usd)usd.onclick=()=>{state.currency='USD';localStorage.setItem('bg_cur','USD');render()};render()})();